# Generated by Django 2.0.1 on 2018-04-30 07:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0003_bookinstance_borrower'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('FileCode', models.CharField(max_length=200)),
                ('Src1', models.CharField(max_length=10)),
                ('Src2', models.CharField(max_length=10)),
                ('Src3', models.CharField(max_length=10)),
                ('Des1', models.CharField(max_length=10)),
                ('Des2', models.CharField(max_length=10)),
                ('Des3', models.CharField(max_length=10)),
                ('DepartureDate', models.DateField(null=True)),
                ('RetrunDate', models.DateField(null=True)),
                ('status', models.IntegerField(max_length=1, null=True)),
                ('Discription', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
